name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip mypy
        pip install -r api/requirements.txt

    - name: Run unit tests
      env:
        FLASK_ENV: test
      working-directory: api/app/
      run: |
        python test_app.py

    - name: Type check with mypy
      env:
        FLASK_ENV: test
      working-directory: api/app/
      run: mypy flask_app.py model.py --explicit-package-bases --ignore-missing-imports

